name: run tests
on: [push,pull_request] 
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6,3.7,3.8]
        os: [macOS-latest, ubuntu-latest]
    steps:
        - name: checkout
          uses: actions/checkout@v2
          with:
            repository: 'Wolflink/search_compiler'
            ref: dev
        - name: setup python
          uses: actions/setup-python@v1
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install nightly-2020-01-23
          uses: actions-rs/toolchain@v1
          with:
              toolchain: nightly-2020-01-23
              override: true
        - name: Install blas/gfortran (ubuntu)
          run: sudo apt install libopenblas-dev libgfortran-dev
          if: matrix.os == "ubuntu-latest"
        - name: Install blas/gfortran (macOS)
          run: brew install gcc openblas
          if: matrix.os == "macOS-latest"
        - name: Test building & installing Rust extension
          run: cd native && pip install . && cd ..

        - name: Test installed package is importable
          run: python -c 'import search_compiler_rs'
